# Image Size: 221MB
# Linux + Node + Source + Project dependencies
FROM node:current-alpine as base
WORKDIR /app
COPY package.json ./
RUN yarn install
COPY . .

# Linux + Node + Source + Project dependencies + build assets
FROM base AS build
ENV NODE_ENV=production
WORKDIR /build
COPY --from=base /app ./
RUN yarn run build


EXPOSE 3000
CMD yarn run start
