FROM node:latest

# ENV NODE_ENV=development
# ARG NEXT_PUBLIC_API_URL
# ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN mkdir -p /app
WORKDIR /app
COPY package*.json ./
# COPY yarn.lock ./
RUN yarn install
COPY . . 
# RUN yarn build
EXPOSE 3000
CMD ["yarn", "dev"]