/*eslint-disable*/

// import type { NextPage } from "next";
// import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{" "}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{" "}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   );
// };

// export default Home;

import React from 'react';
import { gql } from '@apollo/client';
import client from '../apollo-client';
import { Grid, ListItemText } from '@material-ui/core';
import styles from '../styles/Home.module.css';
import List from '@material-ui/core/List';
import ListItem from '@material-ui/core/ListItem';
import Divider from '@material-ui/core/Divider';
import ListItemAvatar from '@material-ui/core/ListItemAvatar';
import Avatar from '@material-ui/core/Avatar';
import Typography from '@material-ui/core/Typography';
import axios from 'axios';
import ProductCard from '../components/Shop/ProductCard';
import Base from '../components/Layouts/Base';
import CategoryCard from '../components/Shop/CategoryCard';

export async function getStaticProps() {
  const res: any = await axios.get('http://localhost:8080/api/v1/category');
  if (res.status === 200) {
    return {
      props: {
        categories: res.data,
      },
    };
  }
}

const Products = ({ products, cols = 12 }: any) => {
  return (
    <React.Fragment>
      {products &&
        products.map((product: any) => {
          return (
            <div key={product._id} className={`col-md-${cols}`}>
              <ProductCard
                key={`productCard_${product._id}`}
                product={product}
              />
            </div>
          );
        })}
    </React.Fragment>
  );
};

export default function Home({ categories }: any) {
  const CategoriesProduct = () => {
    return (
      <>
        {categories.map((cat: any) => {
          return (
            <React.Fragment key={cat._id}>
              <h3>{cat.name}</h3>
              <Products products={cat.products.slice(0, 3)} cols={4} />
            </React.Fragment>
          );
        })}
      </>
    );
  };

  const TopCategories = () => {
    return (
      <div className="row">
        <div className="col-md-12 text-center mt-5 mb-5">
          <h3 className="text-success">Top Categories</h3>
        </div>
        {categories.map((cat: any) => {
          return (
            <div
              key={cat._id}
              className="col-md-3 "
              style={{ height: '300px' }}
            >
              <CategoryCard category={cat} />
            </div>
          );
        })}
      </div>
    );
  };

  const BestSelling = () => {
    return (
      <div className="row">
        <div className="col-md-12 text-center mt-5 mb-5 ">
          <h3 className="text-success">Best Selling</h3>
        </div>
        {categories.map((cat: any) => {
          return (
            <div
              key={cat._id}
              className="col-md-3 "
              style={{ height: '300px' }}
            >
              <CategoryCard category={cat} />
            </div>
          );
        })}
      </div>
    );
  };

  const Content = () => {
    return (
      <>
        <TopCategories />
        <BestSelling />
        <CategoriesProduct />
      </>
    );
  };
  return <Base Component={() => <Content />}></Base>;
}
